[package]
name = "elvis"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version = "4.5.53", features = ["derive"]}
console = "0.16.2"
dialoguer = "0.12.0"
filetime = "0.2.26"
walkdir = "2.5.0"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
tempfile = "3"
